server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
banner:
  charset: utf-8
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  messages:
    encoding: UTF-8
  mail:
    host: smtp.163.com
    username: coincide88@163.com
    password: XPUVUHPFSYOPALAS
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
filePath: F:/test/
thymeleaf:
  prefix: classpath:/templates  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5


